/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.temporada;

/**
 *
 * @author Daniel bonilla
 */
public class TemporadaPanel extends javax.swing.JPanel {

    /**
     * Creates new form TemporadaPanel
     */
    public TemporadaPanel() {
        initComponents();

    }

    public void cargarTabla(java.util.List<modelo.Temporada> lista) {
        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) tblTemporadas.getModel();

        modelo.setRowCount(0);

        for (modelo.Temporada t : lista) {
            modelo.addRow(new Object[]{
                t.getId(),
                t.getNombre(),
                t.getFechaInicio(),
                t.getFechaFin(),
                t.getRecargo()
            });
        }
    }

    public modelo.Temporada getTemporadaSeleccionada() {

        int fila = tblTemporadas.getSelectedRow();
        if (fila == -1) {
            return null;
        }

        modelo.Temporada t = new modelo.Temporada();
        t.setId(Integer.parseInt(tblTemporadas.getValueAt(fila, 0).toString()));
        t.setNombre(tblTemporadas.getValueAt(fila, 1).toString());
        t.setFechaInicio(tblTemporadas.getValueAt(fila, 2).toString());
        t.setFechaFin(tblTemporadas.getValueAt(fila, 3).toString());
        t.setRecargo(Double.parseDouble(tblTemporadas.getValueAt(fila, 4).toString()));

        return t;
    }

    // ======================================================================
// Cargar datos en la tabla
// ======================================================================
    public void actualizarTabla(java.util.List<modelo.Temporada> lista) {
        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) tblTemporadas.getModel();

        modelo.setRowCount(0); // Limpia la tabla

        for (modelo.Temporada t : lista) {
            modelo.addRow(new Object[]{
                t.getId(),
                t.getNombre(),
                t.getFechaInicio(),
                t.getFechaFin(),
                t.getRecargo() + "%"
            });
        }
    }

// ======================================================================
// Obtener ID seleccionado de la tabla
// ======================================================================
    public int getIdSeleccionado() {
        int fila = tblTemporadas.getSelectedRow();
        if (fila == -1) {
            return -1;
        }

        return Integer.parseInt(tblTemporadas.getValueAt(fila, 0).toString());
    }

// ======================================================================
// Limpiar el campo de búsqueda (opcional pero útil)
// ======================================================================
    public void limpiarBusqueda() {
        txtBuscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTemporadas = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1150, 650));
        setPreferredSize(new java.awt.Dimension(1150, 650));

        jLabel1.setText("Buscar:");

        btnBuscar.setText("🔎 Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnNuevo.setText("➕ Nuevo");

        btnEditar.setText("✏ Editar");

        btnEliminar.setText("❌ Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tblTemporadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha Inicio", "Fecha Fin", "Recargo"
            }
        ));
        jScrollPane1.setViewportView(tblTemporadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(171, 171, 171)
                .addComponent(btnNuevo)
                .addGap(50, 50, 50)
                .addComponent(btnEditar)
                .addGap(50, 50, 50)
                .addComponent(btnEliminar)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1144, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblTemporadas;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
